# Generated by Django 6.1.1 on 2026-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecontent',
            options={'verbose_name': 'Контент статьи', 'verbose_name_plural': 'Контент статей'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='дата написание содержания статьи'),
        ),
    ]
