# Generated by Django 6.1.1 on 2026-09-14 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_articlecontent_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlecontents', to='core.article', verbose_name='К какой статье?'),
        ),
    ]
