# Generated by Django 6.1.1 on 2026-09-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_articlecontent_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='alt',
            field=models.CharField(max_length=255, null=True, verbose_name='если картинка не отображается выводит этот текст'),
        ),
    ]
