# Generated by Django 6.1.1 on 2026-09-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='если картинка не отображается выводит этот текст'),
        ),
    ]
